import "./globals.css";
import Header from "./Components/Header.jsx";
import Footer from "./footer/page.jsx"; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Header/> */}

      <body
        className={'font-sans antialiased'}
      >
        {children}
      </body>

      {/* <Footer/> */}
    </html>
  );
}
